(define container (document-query-selector "#root"))

(define (init)
  '())

(define (login model mc)
  '(div (@ (id . "root"))
        (h1 "Incoming " (small "yet another webmail application"))
        (div (@ (id . "login") (class . "box"))
             (h2 "Login")
             (p (input (@ (type . "text") (placeholder . "username"))))
             (p (button (@ (type . "submit")) "Submit")))))

(define (view model mc)
  '(div (@ (id . "inbox"))
        (h1 "Incoming " (small "yet another webmail application"))
        (div (p (input (@ (type . "text") (placeholder . "🔎 Search your emails")))))
        (div (@ (class . "bundle box"))
             (p (@ (class . "bundle-name")) "💬 Mailling list")
             (p (@ (class . "bundle-description"))
                (span (@ (class . "bundle-new")) "25+ new")
                (span "Alan Kay, Donald Knuth, Dijkstra...")))
        (div (@ (class . "bundle box"))
             (p (@ (class . "bundle-name")) "👾 Spam")
             (p (@ (class . "bundle-description"))
                (span (@ (class . "bundle-new")) "25+ new")
                (span "Ebay, LinkedIn, Amazon...")))))

(create-app container init view)
